/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import java.util.*;
import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class AArgumentList extends PArgumentList
{
    private PArgument _argument_;
    private final LinkedList<PArgumentListTail> _argumentListTail_ = new LinkedList<PArgumentListTail>();

    public AArgumentList()
    {
        // Constructor
    }

    public AArgumentList(
        @SuppressWarnings("hiding") PArgument _argument_,
        @SuppressWarnings("hiding") List<?> _argumentListTail_)
    {
        // Constructor
        setArgument(_argument_);

        setArgumentListTail(_argumentListTail_);

    }

    @Override
    public Object clone()
    {
        return new AArgumentList(
            cloneNode(this._argument_),
            cloneList(this._argumentListTail_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArgumentList(this);
    }

    public PArgument getArgument()
    {
        return this._argument_;
    }

    public void setArgument(PArgument node)
    {
        if(this._argument_ != null)
        {
            this._argument_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._argument_ = node;
    }

    public LinkedList<PArgumentListTail> getArgumentListTail()
    {
        return this._argumentListTail_;
    }

    public void setArgumentListTail(List<?> list)
    {
        for(PArgumentListTail e : this._argumentListTail_)
        {
            e.parent(null);
        }
        this._argumentListTail_.clear();

        for(Object obj_e : list)
        {
            PArgumentListTail e = (PArgumentListTail) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._argumentListTail_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._argument_)
            + toString(this._argumentListTail_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._argument_ == child)
        {
            this._argument_ = null;
            return;
        }

        if(this._argumentListTail_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._argument_ == oldChild)
        {
            setArgument((PArgument) newChild);
            return;
        }

        for(ListIterator<PArgumentListTail> i = this._argumentListTail_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PArgumentListTail) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
