/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class AConcatExpressionLvl5 extends PExpressionLvl5
{
    private PExpressionLvl5 _expressionLvl5_;
    private TConcatenate _concatenate_;
    private PExpressionLvl4 _expressionLvl4_;

    public AConcatExpressionLvl5()
    {
        // Constructor
    }

    public AConcatExpressionLvl5(
        @SuppressWarnings("hiding") PExpressionLvl5 _expressionLvl5_,
        @SuppressWarnings("hiding") TConcatenate _concatenate_,
        @SuppressWarnings("hiding") PExpressionLvl4 _expressionLvl4_)
    {
        // Constructor
        setExpressionLvl5(_expressionLvl5_);

        setConcatenate(_concatenate_);

        setExpressionLvl4(_expressionLvl4_);

    }

    @Override
    public Object clone()
    {
        return new AConcatExpressionLvl5(
            cloneNode(this._expressionLvl5_),
            cloneNode(this._concatenate_),
            cloneNode(this._expressionLvl4_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConcatExpressionLvl5(this);
    }

    public PExpressionLvl5 getExpressionLvl5()
    {
        return this._expressionLvl5_;
    }

    public void setExpressionLvl5(PExpressionLvl5 node)
    {
        if(this._expressionLvl5_ != null)
        {
            this._expressionLvl5_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressionLvl5_ = node;
    }

    public TConcatenate getConcatenate()
    {
        return this._concatenate_;
    }

    public void setConcatenate(TConcatenate node)
    {
        if(this._concatenate_ != null)
        {
            this._concatenate_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._concatenate_ = node;
    }

    public PExpressionLvl4 getExpressionLvl4()
    {
        return this._expressionLvl4_;
    }

    public void setExpressionLvl4(PExpressionLvl4 node)
    {
        if(this._expressionLvl4_ != null)
        {
            this._expressionLvl4_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressionLvl4_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressionLvl5_)
            + toString(this._concatenate_)
            + toString(this._expressionLvl4_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressionLvl5_ == child)
        {
            this._expressionLvl5_ = null;
            return;
        }

        if(this._concatenate_ == child)
        {
            this._concatenate_ = null;
            return;
        }

        if(this._expressionLvl4_ == child)
        {
            this._expressionLvl4_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expressionLvl5_ == oldChild)
        {
            setExpressionLvl5((PExpressionLvl5) newChild);
            return;
        }

        if(this._concatenate_ == oldChild)
        {
            setConcatenate((TConcatenate) newChild);
            return;
        }

        if(this._expressionLvl4_ == oldChild)
        {
            setExpressionLvl4((PExpressionLvl4) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
