/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class AExpression extends PExpression
{
    private PExpressionLvl8 _expressionLvl8_;

    public AExpression()
    {
        // Constructor
    }

    public AExpression(
        @SuppressWarnings("hiding") PExpressionLvl8 _expressionLvl8_)
    {
        // Constructor
        setExpressionLvl8(_expressionLvl8_);

    }

    @Override
    public Object clone()
    {
        return new AExpression(
            cloneNode(this._expressionLvl8_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpression(this);
    }

    public PExpressionLvl8 getExpressionLvl8()
    {
        return this._expressionLvl8_;
    }

    public void setExpressionLvl8(PExpressionLvl8 node)
    {
        if(this._expressionLvl8_ != null)
        {
            this._expressionLvl8_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressionLvl8_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressionLvl8_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressionLvl8_ == child)
        {
            this._expressionLvl8_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expressionLvl8_ == oldChild)
        {
            setExpressionLvl8((PExpressionLvl8) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
