/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class AGreaterExpressionLvl6 extends PExpressionLvl6
{
    private PExpressionLvl5 _first_;
    private TGreater _greater_;
    private PExpressionLvl5 _second_;

    public AGreaterExpressionLvl6()
    {
        // Constructor
    }

    public AGreaterExpressionLvl6(
        @SuppressWarnings("hiding") PExpressionLvl5 _first_,
        @SuppressWarnings("hiding") TGreater _greater_,
        @SuppressWarnings("hiding") PExpressionLvl5 _second_)
    {
        // Constructor
        setFirst(_first_);

        setGreater(_greater_);

        setSecond(_second_);

    }

    @Override
    public Object clone()
    {
        return new AGreaterExpressionLvl6(
            cloneNode(this._first_),
            cloneNode(this._greater_),
            cloneNode(this._second_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGreaterExpressionLvl6(this);
    }

    public PExpressionLvl5 getFirst()
    {
        return this._first_;
    }

    public void setFirst(PExpressionLvl5 node)
    {
        if(this._first_ != null)
        {
            this._first_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._first_ = node;
    }

    public TGreater getGreater()
    {
        return this._greater_;
    }

    public void setGreater(TGreater node)
    {
        if(this._greater_ != null)
        {
            this._greater_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._greater_ = node;
    }

    public PExpressionLvl5 getSecond()
    {
        return this._second_;
    }

    public void setSecond(PExpressionLvl5 node)
    {
        if(this._second_ != null)
        {
            this._second_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._second_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._first_)
            + toString(this._greater_)
            + toString(this._second_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._first_ == child)
        {
            this._first_ = null;
            return;
        }

        if(this._greater_ == child)
        {
            this._greater_ = null;
            return;
        }

        if(this._second_ == child)
        {
            this._second_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._first_ == oldChild)
        {
            setFirst((PExpressionLvl5) newChild);
            return;
        }

        if(this._greater_ == oldChild)
        {
            setGreater((TGreater) newChild);
            return;
        }

        if(this._second_ == oldChild)
        {
            setSecond((PExpressionLvl5) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
