/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class AInheritsClause extends PInheritsClause
{
    private TInherits _inherits_;
    private TFrom _from_;
    private TIdentifier _identifier_;

    public AInheritsClause()
    {
        // Constructor
    }

    public AInheritsClause(
        @SuppressWarnings("hiding") TInherits _inherits_,
        @SuppressWarnings("hiding") TFrom _from_,
        @SuppressWarnings("hiding") TIdentifier _identifier_)
    {
        // Constructor
        setInherits(_inherits_);

        setFrom(_from_);

        setIdentifier(_identifier_);

    }

    @Override
    public Object clone()
    {
        return new AInheritsClause(
            cloneNode(this._inherits_),
            cloneNode(this._from_),
            cloneNode(this._identifier_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInheritsClause(this);
    }

    public TInherits getInherits()
    {
        return this._inherits_;
    }

    public void setInherits(TInherits node)
    {
        if(this._inherits_ != null)
        {
            this._inherits_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._inherits_ = node;
    }

    public TFrom getFrom()
    {
        return this._from_;
    }

    public void setFrom(TFrom node)
    {
        if(this._from_ != null)
        {
            this._from_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._from_ = node;
    }

    public TIdentifier getIdentifier()
    {
        return this._identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(this._identifier_ != null)
        {
            this._identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifier_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._inherits_)
            + toString(this._from_)
            + toString(this._identifier_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._inherits_ == child)
        {
            this._inherits_ = null;
            return;
        }

        if(this._from_ == child)
        {
            this._from_ = null;
            return;
        }

        if(this._identifier_ == child)
        {
            this._identifier_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._inherits_ == oldChild)
        {
            setInherits((TInherits) newChild);
            return;
        }

        if(this._from_ == oldChild)
        {
            setFrom((TFrom) newChild);
            return;
        }

        if(this._identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
