/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class AOrExpressionLvl8 extends PExpressionLvl8
{
    private PExpressionLvl8 _expressionLvl8_;
    private TOr _or_;
    private PExpressionLvl7 _expressionLvl7_;

    public AOrExpressionLvl8()
    {
        // Constructor
    }

    public AOrExpressionLvl8(
        @SuppressWarnings("hiding") PExpressionLvl8 _expressionLvl8_,
        @SuppressWarnings("hiding") TOr _or_,
        @SuppressWarnings("hiding") PExpressionLvl7 _expressionLvl7_)
    {
        // Constructor
        setExpressionLvl8(_expressionLvl8_);

        setOr(_or_);

        setExpressionLvl7(_expressionLvl7_);

    }

    @Override
    public Object clone()
    {
        return new AOrExpressionLvl8(
            cloneNode(this._expressionLvl8_),
            cloneNode(this._or_),
            cloneNode(this._expressionLvl7_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOrExpressionLvl8(this);
    }

    public PExpressionLvl8 getExpressionLvl8()
    {
        return this._expressionLvl8_;
    }

    public void setExpressionLvl8(PExpressionLvl8 node)
    {
        if(this._expressionLvl8_ != null)
        {
            this._expressionLvl8_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressionLvl8_ = node;
    }

    public TOr getOr()
    {
        return this._or_;
    }

    public void setOr(TOr node)
    {
        if(this._or_ != null)
        {
            this._or_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._or_ = node;
    }

    public PExpressionLvl7 getExpressionLvl7()
    {
        return this._expressionLvl7_;
    }

    public void setExpressionLvl7(PExpressionLvl7 node)
    {
        if(this._expressionLvl7_ != null)
        {
            this._expressionLvl7_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressionLvl7_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressionLvl8_)
            + toString(this._or_)
            + toString(this._expressionLvl7_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressionLvl8_ == child)
        {
            this._expressionLvl8_ = null;
            return;
        }

        if(this._or_ == child)
        {
            this._or_ = null;
            return;
        }

        if(this._expressionLvl7_ == child)
        {
            this._expressionLvl7_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expressionLvl8_ == oldChild)
        {
            setExpressionLvl8((PExpressionLvl8) newChild);
            return;
        }

        if(this._or_ == oldChild)
        {
            setOr((TOr) newChild);
            return;
        }

        if(this._expressionLvl7_ == oldChild)
        {
            setExpressionLvl7((PExpressionLvl7) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
