/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class AOtherExpressionLvl7 extends PExpressionLvl7
{
    private PExpressionLvl6 _expressionLvl6_;

    public AOtherExpressionLvl7()
    {
        // Constructor
    }

    public AOtherExpressionLvl7(
        @SuppressWarnings("hiding") PExpressionLvl6 _expressionLvl6_)
    {
        // Constructor
        setExpressionLvl6(_expressionLvl6_);

    }

    @Override
    public Object clone()
    {
        return new AOtherExpressionLvl7(
            cloneNode(this._expressionLvl6_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOtherExpressionLvl7(this);
    }

    public PExpressionLvl6 getExpressionLvl6()
    {
        return this._expressionLvl6_;
    }

    public void setExpressionLvl6(PExpressionLvl6 node)
    {
        if(this._expressionLvl6_ != null)
        {
            this._expressionLvl6_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressionLvl6_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressionLvl6_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressionLvl6_ == child)
        {
            this._expressionLvl6_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expressionLvl6_ == oldChild)
        {
            setExpressionLvl6((PExpressionLvl6) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
