/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class ASubtractExpressionLvl4 extends PExpressionLvl4
{
    private PExpressionLvl4 _expressionLvl4_;
    private TMinus _minus_;
    private PExpressionLvl3 _expressionLvl3_;

    public ASubtractExpressionLvl4()
    {
        // Constructor
    }

    public ASubtractExpressionLvl4(
        @SuppressWarnings("hiding") PExpressionLvl4 _expressionLvl4_,
        @SuppressWarnings("hiding") TMinus _minus_,
        @SuppressWarnings("hiding") PExpressionLvl3 _expressionLvl3_)
    {
        // Constructor
        setExpressionLvl4(_expressionLvl4_);

        setMinus(_minus_);

        setExpressionLvl3(_expressionLvl3_);

    }

    @Override
    public Object clone()
    {
        return new ASubtractExpressionLvl4(
            cloneNode(this._expressionLvl4_),
            cloneNode(this._minus_),
            cloneNode(this._expressionLvl3_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASubtractExpressionLvl4(this);
    }

    public PExpressionLvl4 getExpressionLvl4()
    {
        return this._expressionLvl4_;
    }

    public void setExpressionLvl4(PExpressionLvl4 node)
    {
        if(this._expressionLvl4_ != null)
        {
            this._expressionLvl4_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressionLvl4_ = node;
    }

    public TMinus getMinus()
    {
        return this._minus_;
    }

    public void setMinus(TMinus node)
    {
        if(this._minus_ != null)
        {
            this._minus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._minus_ = node;
    }

    public PExpressionLvl3 getExpressionLvl3()
    {
        return this._expressionLvl3_;
    }

    public void setExpressionLvl3(PExpressionLvl3 node)
    {
        if(this._expressionLvl3_ != null)
        {
            this._expressionLvl3_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressionLvl3_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressionLvl4_)
            + toString(this._minus_)
            + toString(this._expressionLvl3_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressionLvl4_ == child)
        {
            this._expressionLvl4_ = null;
            return;
        }

        if(this._minus_ == child)
        {
            this._minus_ = null;
            return;
        }

        if(this._expressionLvl3_ == child)
        {
            this._expressionLvl3_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expressionLvl4_ == oldChild)
        {
            setExpressionLvl4((PExpressionLvl4) newChild);
            return;
        }

        if(this._minus_ == oldChild)
        {
            setMinus((TMinus) newChild);
            return;
        }

        if(this._expressionLvl3_ == oldChild)
        {
            setExpressionLvl3((PExpressionLvl3) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
