/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class TInherits extends Token
{
    public TInherits()
    {
        super.setText("inherits");
    }

    public TInherits(int line, int pos)
    {
        super.setText("inherits");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TInherits(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTInherits(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TInherits text.");
    }
}
