/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class TMe extends Token
{
    public TMe()
    {
        super.setText("me");
    }

    public TMe(int line, int pos)
    {
        super.setText("me");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TMe(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMe(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TMe text.");
    }
}
